# Generated by Django 3.1.7 on 2021-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad_tutor',
            old_name='extecpted_salary',
            new_name='expected_salary',
        ),
    ]
