# Generated by Django 3.2 on 2021-05-04 11:35

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('class_code', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=550, null=True)),
                ('image', models.ImageField(blank=True, upload_to=courses.models.save_class_image, verbose_name='class image')),
                ('students', models.ManyToManyField(blank=True, to='home.Student')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='home.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=550, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Lecture No')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=courses.models.save_lecture_files, verbose_name='video')),
                ('ppt', models.FileField(blank=True, upload_to=courses.models.save_lecture_files, verbose_name='ppt')),
                ('notes', models.FileField(blank=True, upload_to=courses.models.save_lecture_files, verbose_name='notes')),
                ('class_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='home.tutor')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
