# Generated by Django 3.1.7 on 2021-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20210411_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_student',
            name='days',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='ad_student',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Ad_Tutor',
        ),
    ]
