# Generated by Django 3.1.7 on 2021-05-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0005_auto_20210428_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('class_level', models.CharField(blank=True, max_length=150, null=True)),
                ('days', models.DecimalField(decimal_places=0, default=2, max_digits=2)),
                ('salary', models.CharField(default=3000, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_confirmation', models.BooleanField(default=False)),
                ('ad_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('expected_area', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('class_level', models.CharField(blank=True, max_length=150, null=True)),
                ('days', models.DecimalField(decimal_places=0, default=2, max_digits=7)),
                ('expected_salary', models.CharField(default=3000, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_confirmation', models.BooleanField(default=False)),
                ('ad_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad_tutor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ad_Student',
        ),
        migrations.DeleteModel(
            name='Ad_Tutor',
        ),
    ]
