# Generated by Django 3.1.7 on 2021-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20210502_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_student',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='ad_student',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_tutor',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ad_tutor',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
