# Generated by Django 3.1.7 on 2021-05-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20210505_1416'),
        ('ad', '0012_auto_20210504_0315'),
    ]

    operations = [
    ]
